apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
spec:
  selector:
    matchLabels:
      app: front-end-app
  replicas: 2
  template:
    metadata:
      labels:
        app: front-end-app
    spec:
      containers:
        - name: front-end
          image: foo:0.0.1
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          ports:
            - containerPort: 80
              protocol: TCP