apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-end-svc
  name: front-end-app
  namespace: default
spec:
  type: LoadBalancer    # use ClusterIP as type here
  ports:
    - port: 8080
  selector:
    app: front-end-app